name: gh-action_jira-create
description: Create a new Jira issue
inputs:
  project:
    description: Key of the project
    required: true
  issuetype:
    description: "Type of the issue to be created. Example: 'Task'"
    required: true
  summary:
    description: Issue summary
    required: true
  description:
    description: Issue description
    required: false
  fields:
    description: Additional fields in JSON format
    required: false
outputs:
  issue:
    description: Key of the newly created issue
    value: ${{ steps.create.outputs.issue }}

runs:
  using: composite
  steps:
    - uses: peter-evans/jira2md@71f20480efa44538956efcce4f764e7e8f959781 # v2.0.0
      id: md2jira
      with:
        input-text: ${{ inputs.description }}
        mode: md2jira
    - name: Create Jira issue
      id: create
      uses: atlassian/gajira-create@1ff0b6bd115a780592b47bfbb63fc4629132e6ec # v3
      with:
        project: ${{ inputs.project }}
        issuetype: ${{ inputs.issuetype }}
        summary: ${{ inputs.summary }}
        description: ${{ steps.md2jira.outputs.output-text }}
        fields: ${{ inputs.fields }}
